// nature-data.js
// ไพ่รหัสลับแห่งผืนดิน 30 ใบ — แยกออกมาจาก oracle-nature.html เดิม
var NATURE_CARDS = [
  {id:'c1',name:'The Seed',meaning:'จุดเริ่มต้น ไอเดียใหม่',img:'../images/nature/c1.png'},
  {id:'c2',name:'The Root',meaning:'พื้นฐาน ความมั่นคง',img:'../images/nature/c2.png'},
  {id:'c3',name:'The Tree',meaning:'เติบโต แข็งแกร่ง',img:'../images/nature/c3.png'},
  {id:'c4',name:'The River',meaning:'ไหลลื่น ปล่อยวาง',img:'../images/nature/c4.png'},
  {id:'c5',name:'The Stone',meaning:'นิ่ง อดทน มั่นคง',img:'../images/nature/c5.png'},
  {id:'c6',name:'The Rain',meaning:'เยียวยา ชำระล้าง',img:'../images/nature/c6.png'},
  {id:'c7',name:'The Mist',meaning:'ไม่ชัดเจน ลังเล',img:'../images/nature/c7.png'},
  {id:'c8',name:'The Bloom',meaning:'เปิดใจ บาน ความงาม',img:'../images/nature/c8.png'},
  {id:'c9',name:'The Wind',meaning:'เปลี่ยนแปลง อิสระ',img:'../images/nature/c9.png'},
  {id:'c10',name:'The Firefly',meaning:'ความหวังเล็กๆ แสงในมืด',img:'../images/nature/c10.png'},
  {id:'s1',name:'The Storm',meaning:'วุ่นวาย ปัญหา',img:'../images/nature/s1.png'},
  {id:'s2',name:'The Drought',meaning:'หมดแรง ขาดแคลน',img:'../images/nature/s2.png'},
  {id:'s3',name:'The Crossroad',meaning:'ทางแยก ตัดสินใจ',img:'../images/nature/s3.png'},
  {id:'s4',name:'The Fall',meaning:'จบบางอย่าง ปล่อย',img:'../images/nature/s4.png'},
  {id:'s5',name:'The Tide',meaning:'ขึ้นลง ไม่เสถียร',img:'../images/nature/s5.png'},
  {id:'s6',name:'The Shadow',meaning:'กลัว ความมืด',img:'../images/nature/s6.png'},
  {id:'s7',name:'The Echo',meaning:'เรื่องเดิมวนซ้ำ',img:'../images/nature/s7.png'},
  {id:'s8',name:'The Web',meaning:'ติดกับดัก พันธนาการ',img:'../images/nature/s8.png'},
  {id:'s9',name:'The Cliff',meaning:'เสี่ยง กดดัน วิกฤต',img:'../images/nature/s9.png'},
  {id:'s10',name:'The Cocoon',meaning:'ช่วงเปลี่ยนผ่าน',img:'../images/nature/s10.png'},
  {id:'a1',name:'Nurture',meaning:'ดูแล ใส่ใจ',img:'../images/nature/a1.png'},
  {id:'a2',name:'Wait',meaning:'รอจังหวะ อย่าเร่ง',img:'../images/nature/a2.png'},
  {id:'a3',name:'Release',meaning:'ปล่อยวาง ตัด',img:'../images/nature/a3.png'},
  {id:'a4',name:'Move',meaning:'ลงมือทำ เริ่มเลย',img:'../images/nature/a4.png'},
  {id:'a5',name:'Listen',meaning:'ฟังข้างใน เสียงจิตใจ',img:'../images/nature/a5.png'},
  {id:'a6',name:'Protect',meaning:'ปกป้องตัวเอง',img:'../images/nature/a6.png'},
  {id:'a7',name:'Adapt',meaning:'ปรับตัว ยืดหยุ่น',img:'../images/nature/a7.png'},
  {id:'a8',name:'Focus',meaning:'โฟกัส ตั้งใจ',img:'../images/nature/a8.png'},
  {id:'a9',name:'Cleanse',meaning:'เคลียร์พลังลบ',img:'../images/nature/a9.png'},
  {id:'a10',name:'Trust',meaning:'เชื่อในตัวเอง',img:'../images/nature/a10.png'},
];